### ISSUE TITLE
liferay-theme-tasks 10.0.0-alpha.1+gulp 4.0.0 - UnhandledPromiseRejectionWarning when running 'gulp watch'

### ISSUE THREAD

**Issue by zhangyan0701** [liferay/liferay-js-themes-toolkit#459] opened 2020-04-01 13:16 UTC
**Steps to reproduce:**

1. Generate a theme with JS Theme Toolkit v9.5.0.
2. Edit the theme's package.json and point liferay-theme-tasks to "10.0.0-alpha.1" and gulp to "^4.0.0".
3. rm -rf node_modules (just in case).
4. rm package-lock.json (just in case).
5. Run npm install again.
6. Navigate to theme's root folder.
7. Make an edit to to file _custom.scss.
```
html body {
    background-color:green;
}
```
8. Run 'gulp deploy'.
9. Start liferay.
10. Apply theme to a site.
11. Navigate to theme’s root folder.
12. Run 'gulp watch'.

Expected Result:
No warning message in console.

Actual Result:
UnhandledPromiseRejectionWarning is thrown, but this warning doesn't affect the function.
![gulp watch-linux](https://user-images.githubusercontent.com/25576873/78141350-f5a17080-745d-11ea-84e2-e0e71181267e.png)

**Comment by izaera** [comment] 2020-04-02 12:32
I cannot reproduce it and I cannot see any information in the stack trace of what could be happening. 

Can you provide more info @zhangyan0701? 

If not, maybe you can test it in a different machine to see what happens. Or we can close it, given that it doesn't alter the functionality...

**Comment by zhangyan0701** [comment] 2020-04-03 11:56
Hi @izaera, 

Thanks for working on this! I changed to test on CentOS 7 VM instead of a docker image, and didn't see this warning message. The gulp watch worked as expected. I will close this issue.

Regards!

**Closed** 2020-04-03 11:57 UTC
Labels: bug, needs repro
